// src/flight/components/Signup.jsx
import React from 'react'

export default function Signup(props) {
  
  const userModel = {
    userName: '',
    password: '',
    repassword: '',
    cardID: '',
    telephone: '',
    email: '',
    role: 1,
  }

  const setName = (ev) => {
    userModel.userName = ev.target.value
  }
  const setPwd = (ev) => {
    userModel.password = ev.target.value
  }
  const setCPwd = (ev) => {
    userModel.repassword = ev.target.value
  }
  const setCard = (ev) => {
    userModel.cardID = ev.target.value
  }
  const setTele = (ev) => {
    userModel.telephone = ev.target.value
  }
  const setEmail = (ev) => {
    userModel.email = ev.target.value
  }
  const setRole = (ev) => {
    userModel.role = ev.target.value
  }
  
  const SigninToggle = () => {
    props.SigninToggle()
  }
  const toggleInOrUp = () => {
    props.toggleInOrUp('in')
  }

  const handleSignup = () => {
    props.handleSignup(userModel)
  }

  return (
    <div>
      <div className="mask"></div>
      <div className="popup-wrap">
        <header>
          <h3>注 册</h3>
          <i onClick={ SigninToggle }>X</i>
        </header>
        <div className="popup-body">
          <p>
            <label>用户名：</label>
            <input type="text" onChange={ setName } />
          </p>
          <p>
            <label>密 码：</label>
            <input type="password" onChange={ setPwd } />
          </p>
          <p>
            <label>确认密码：</label>
            <input type="password" onChange={ setCPwd } />
          </p>
          <p>
            <label>身份证：</label>
            <input type="number" onChange={ setCard } />
          </p>
          <p>
            <label>手机号：</label>
            <input type="number" onChange={ setTele } />
          </p>
          <p>
            <label>邮 箱：</label>
            <input type="email" onChange={ setEmail } />
          </p>
          <p>
            <label>角 色：</label>
            <span>
              <input type="radio" name="role" onChange={ setRole } value="1" defaultChecked />普通用户
              <input type="radio" name="role" onChange={ setRole } value="2" />管理员
            </span>
          </p>
          <p className="submit">
            <input type="button" value="注 册" onClick={ handleSignup } />
          </p>
          <p className="submit">
            <input type="button" value="登 录" onClick={ toggleInOrUp } />
          </p>
        </div>
      </div>
    </div>
  )
}

// src/admin/views/SignUp.vue
<script setup>
  import { ref, reactive } from 'vue'
  import { useRouter } from 'vue-router'

  import http from '../util/http'

  const router = useRouter()

  const userModel = reactive({
    userName: '',
    password: '',
    repassword: '',
    cardID: '',
    telephone: '',
    email: '',
    role: 1,
  })

  const handleSignup = () => {
    let canSubmit = true
    Object.keys(userModel).map(item => !userModel[item] && (canSubmit = false))
    if (!canSubmit) {
      alert('不能为空')
    } else {
      http.post(`/user/signup`, userModel).then(res => {
        localStorage.token = res.data.token
        localStorage.user = JSON.stringify(res.data.user)
        router.push('/admin')
      })
    }
  }

  const handleSignin = () => {
    router.push('/admin/user/signin')
  }
</script>

<template>
  <div class="signup">
    <div class="flightAdd">
      <header>
        <h3>注 册</h3>
      </header>
      <div class="addBody">
        <p>
          <label>用户名：</label>
          <input v-model="userModel.userName" />
        </p>
        <p>
          <label>密 码：</label>
          <input type="password" v-model="userModel.password" />
        </p>
        <p>
          <label>确认密码：</label>
          <input type="password" v-model="userModel.repassword" />
        </p>
        <p>
          <label>身份证：</label>
          <input type="number" v-model="userModel.cardID" />
        </p>
        <p>
          <label>手机号：</label>
          <input type="number" v-model="userModel.telephone" />
        </p>
        <p>
          <label>邮 箱：</label>
          <input type="email" v-model="userModel.email" />
        </p>
        <p>
          <label>角 色：</label>
          <span class="radio">
            <input type="radio" v-model="userModel.role" value="1" />普通用户
            <input type="radio" v-model="userModel.role" value="2" />管理员
          </span>
        </p>
        <p class="submit">
          <input type="button" value="注 册" @click="handleSignup" />
        </p>
        <p class="submit">
          <input type="button" value="登 录" @click="handleSignin" />
        </p>
      </div>
    </div>
  </div>
</template>
