// src/flight/components/Signin.jsx
import React from 'react'

export default function Signin(props) {
  
  const userModel = {
    email: '',
    password: ''
  }
  const setEmail = (ev) => {
    userModel.email = ev.target.value
  }
  const setPwd = (ev) => {
    userModel.password = ev.target.value
  }
  const SigninToggle = () => {
    props.SigninToggle()
  }
  const handleSignin = () => {
    props.handleSignin(userModel)
  }

  return (
    <div>
      <div className="mask"></div>
      <div className="popup-wrap">
        <header>
          <h3>登录</h3>
          <i onClick={ SigninToggle }>X</i>
        </header>
        <div className="popup-body">
          <p>
            <label>邮 箱：</label>
            <input type="text" onChange={ setEmail } />
          </p>
          <p>
            <label>密 码：</label>
            <input type="password" onChange={ setPwd } />
          </p>
          <p className="submit">
            <input type="button" value="登 录" onClick={ handleSignin } />
          </p>
        </div>
      </div>
    </div>
  )
}

// src/admin/views/SignIn.vue
<script setup>
  import { ref, reactive } from 'vue'
  import { useRouter } from 'vue-router'

  import http from '../util/http'

  const router = useRouter()

  const userModel = reactive({
    email: '',
    password: ''
  })

  const handleSignin = () => {
    let canSubmit = true
    Object.keys(userModel).map(item => !userModel[item] && (canSubmit = false))
    if (!canSubmit) {
      alert('不能为空')
    } else {
      http.post(`/user/signin`, userModel).then(res => {
        if (res.data.status === 404) {
          alert('用户名或密码错误')
        } else {
          localStorage.token = res.data.token
          localStorage.user = JSON.stringify(res.data.user)
          router.push('/admin')
        }
      })
    }
  }
  
  const handleSignup = () => {
    router.push('/admin/user/signup')
  }
</script>

<template>
  <div class="signin">
    <header>
      <h3>登 录</h3>
    </header>
    <div class="addBody">
      <p>
        <label>邮 箱：</label>
        <input v-model="userModel.email" />
      </p>
      <p>
        <label>密 码：</label>
        <input type="password" v-model="userModel.password" />
      </p>
      <p class="submit">
        <input type="button" value="登录" @click="handleSignin" />
      </p>
      <p class="submit">
        <input type="button" value="注册" @click="handleSignup" />
      </p>
    </div>
  </div>
</template>
